---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fox-peng225-github-io-v1alpha1-pvcbackup
  failurePolicy: Fail
  name: mpvcbackup.kb.io
  rules:
  - apiGroups:
    - fox.peng225.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pvcbackups
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fox-peng225-github-io-v1alpha1-pvcbackup
  failurePolicy: Fail
  name: vpvcbackup.kb.io
  rules:
  - apiGroups:
    - fox.peng225.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pvcbackups
  sideEffects: None
