# permissions for end users to view pvcbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvcbackup-viewer-role
rules:
- apiGroups:
  - fox.peng225.github.io
  resources:
  - pvcbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fox.peng225.github.io
  resources:
  - pvcbackups/status
  verbs:
  - get
