apiVersion: fox.peng225.github.io/v1alpha1
kind: PVCBackup
metadata:
  name: pvcbackup-sample
spec:
  sourcePVC: test-src-pvc
  destinationStorageClass: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-src-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi